version: "3"
services:
  eureka:
    image: bangjinseong/gateway:${BUILD_NUMBER}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_NUMBER
    ports:
      - "9200:9200"