server:
  port: 9200

eureka:
  client:
    service-url:
      defaultZone: http://j9d107.p.ssafy.io:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes: # 사용자 인증과정             - StripPrefix=1             - Method=POST
        - id: dotori-auth-service
          uri: lb://dotori-auth-service
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=0
        - id: dotori-purpose-service
          uri: lb://dotori-purpose-service
          predicates:
            - Path=/api/v1/purpose/**
          filters:
            - StripPrefix=0
        - id: dotori-user-service
          uri: lb://dotori-user-service
          predicates:
            - Path=/api/v1/user/**, /api/v1/oneCent/**
          filters:
            - StripPrefix=0
        - id: dotori-main-service
          uri: lb://dotori-main-service
          predicates:
            - Path=/api/v1/account/**, /api/v1/plan/**, /api/v1/purpose/**, /api/v1/bank/**, /api/v1/chatgpt/**
          filters:
            - StripPrefix=0
            #- RewritePath=/dotori-user-service/(?<segment>.*), /$\{segment}
    config:
      name: dotori
      profile: gateway
  config:
    import: "optional:configserver:http://j9d107.p.ssafy.io:9900/"

  main:
    allow-bean-definition-overriding: true

encrypt:
  key: ${ENCRYPT_KEY}