server:
  port: 9200

eureka:
  client:
    service-url:
      defaultZone: http://j9d107.p.ssafy.io:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: dotori-user-service
          uri: lb://dotori-user-service    # 인증 서버 URI
          predicates:                   # 요청 헤더나 Path 조건 비교
            - Path=/dotori-user-service/**    # 요청 Path
          filters:
            - StripPrefix=1
    config:
      name: dotori
      profile: gateway
  config:
    import: "optional:configserver:http://j9d107.p.ssafy.io:9900/"

  main:
    allow-bean-definition-overriding: true

encrypt:
  key: ${ENCRYPT_KEY}