server:
  port: 9200

eureka:
  client:
    service-url:
      defaultZone: http://j9d107.p.ssafy.io:8761/eureka

spring:
  application:
    name: apigateway-service
#  cloud:
#    gateway:
#      routes:
